apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  namespace: cinemaabyss
  labels:
    app: events-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-api
    spec:
      containers:
      - name: events-api
        image:  ghcr.io/vladimir-kulgun/architecture-pro-cinemaabyss/events-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: ASPNETCORE_URLS
          value: http://+:8082
        - name: KAFKA_BROKERS
          value: kafka:9092
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-api
  namespace: cinemaabyss
spec:
  selector:
    app: events-api
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP